[package]
name = "chain-args"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.5"
anyhow = "1.0"
clap = { version = "4.5", features = ["env", "derive"] }

state-file = { path = "../state-file" }
